baseURL = "https://example.com/"
title = "DFD Responsive Images Module Demo"
copyright = "© 2021 Daniel F. Dickinson"
description = "Demo site for Daniel F. Dickinson's (DFD) responsive images Hugo module"
language = "en"
languageCode = "en-ca"
defaultContentLanguage = "en"
homepage = "https://hugo-dfd-responsive-images.wildtechgarden.ca/"
enableGitInfo = true
enableRobotsTXT = true

[params]
  debugTableEnvironment = ["production","development"]
  mainSections = ["post","docs"]
  testStylesInclude = true
  useBaseURL = false

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.danielfdickinson.ca/"

  [[ author.authors ]]
    name = "Daniel F. Dickinson"
    homepage = "https://www.danielfdickinson.ca/"

[taxonomies]
  category = "categories"
  tag = "tags"

[frontmatter]
  lastmod = ["lastmod",":git",":fileModTime","date","publishDate"]
  date = ["date","publishDate","lastmod",":git",":fileModTime"]
  publishDate = ["publishDate","date","lastmod",":git",":fileModTime"]

[privacy]

  [privacy.vimeo]
    disabled = true

  [privacy.twitter]
    disabled = true

  [privacy.instagram]
    disabled = true

  [privacy.youtube]
    disabled = true

[module]
     [[module.imports]]
        path = "github.com/danielfdickinson/hugo-minimal-test"

     [[module.imports]]
        path = "github.com/danielfdickinson/hugo-dfd-responsive-images"
